## <span style="color:blue">Problem Set 12</span>

### Problem 1

Write a recursive function called **power** that does exponentiation. The function accepts two arguments: num and exp.  The function takes num and raises to the power exp.  The solution does not require any python functions, and obviously should not use the python exponentiation operator.

In [3]:
 def power(num,exp):
    # complete the function
    if exp == 0:
        return 1
    else:
        return num*power(num, exp-1)
    
print("2 to the 8th power is",power(2,8))
print("2 to the 15th power is",power(2,15))

2 to the 8th power is 256
2 to the 15th power is 32768


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
2 to the 8th power is 256<br />
2 to the 15th power is 32768</span>   

### Problem 2

Write a recursive function called **reverse_string** that reverses a string passed as an argument. Do not use any python function to reverse the string.  The string must be reversed by your code.  The only python function required is len().  

In [4]:
def reverse_string(s):
    if len(s) == 0:
        return s
    else:
        return reverse_string(s[1:]) + s[0]

string_to_reverse = "the quick brown fox jumps over the lazy dog"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))
print()
string_to_reverse = "able was I ere I saw elba"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))

The original string: the quick brown fox jumps over the lazy dog
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht

The original string: able was I ere I saw elba
The reversed string: able was I ere I saw elba


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The original string: the quick brown fox jumps over the lazy dog<br />
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht<br />
<br />
The original string: able was I ere I saw elba<br />
The reversed string: able was I ere I saw elba</span>   

### Problem 3

Write a recursive function called **reverse_list** that reverses a list passed as an argument. Do not use any python function to reverse the list.  The list must be reversed by your code.  The only python function required is len().  Hint:  The expression list1 + list2 is a new list consisting of list 2 appended to list 1.

In [5]:
def reverse_list(l):
    if not l: return []
    return [l.pop()]+ reverse_list(l)
       
    
list_to_reverse = [1,2,3,4,5,6,7,8,9,0]
print("The original list:",list_to_reverse)
print("The reversed list:",reverse_list(list_to_reverse))

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]<br />
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]</span>  

### Problem 4

Write a recursive function called **convertToDecimal** that accepts a binary number (string type) and converts it to decimal. Assume a valid binary number is passed so there is not need for error checking.  Also since the binary number passed is a string, you will need to coerce each digit into an integer using the int() function.  This function must work for any binary number of any length, so do not hard code position values.  Position values must be calculated by the function.

The value of the positions for binary numbers are:

    2**n  2**(n-1) ... 2**3  2**2  2**1  2**0   where 2**0 is 1

Determining the decimal value of a binary number:
  1. For each digit, multiply the digit by the value of the position
  2. Repeat step one for all digits in the binary number
  3. Add all the results together
  


In [6]:
def convertToDecimal(binNum):
    if len(binNum) == 0:
        return 0
    else:
        return convertToDecimal(binNum[:-1]) * 2 + int(binNum[-1])
    

bin = '11111111'
print("The binary number",bin,"is",convertToDecimal(bin),"in decimal")
bin = '10101010'
print("The binary number",bin,"is",convertToDecimal(bin),"in decimal")

The binary number 11111111 is 255 in decimal
The binary number 10101010 is 170 in decimal


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The binary number 11111111 is 255 in decimal<br />
The binary number 10101010 is 170 in decimal</span>  