## <span style="color:blue">Problem Set 3</span>

**Note:**   
1. You need to use code to arrive at a solution.  Hardcoding a solution results in 0 points for the problem.
2. **Use only syntax covered in the Units so far.**  Using any other syntax results in 0 points for the problem. 

### Problem 1

In the cell below, write code that iterates over the string _myStr_ and does the following:
1. Print each character.
2. Count the number of characters and stores the result the variable _cntChars_.

Print the variable _myStr_ and _cntChars_ with an appropriate label as shown below in Expected Output.

In [59]:
myStr = "MICHIGAN"

# Write your code below.
for char in myStr:
    print (char)
    
cntChars = len(myStr)
print("The amount of characters in MICHIGAN is", cntChars)

M
I
C
H
I
G
A
N
The amount of characters in MICHIGAN is 8


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
M<br/>
I<br/>
C<br/>
H<br/>
I<br/>
G<br/>
A<br/>
N<br />
The number of characters in MICHIGAN is 8</span>

### Problem 2

In the cell below write one loop that iterates over the list _mixedList_ and does the following:
1. Prints each element and the element type.
2. Count the number of elements and store the result in the variable _cntList_.

Print _cntList_ preceded by an appropriate label as shown below.

In [60]:
mixedList = ["hello", 2, 4, 6.0, 7.5, 234352354, "the end", "", 99]

# Write your code below.
for element in mixedList:
    print (element, type(element))
cntList = len(mixedList)

print("The amount of elements in the list is", cntList)


hello <class 'str'>
2 <class 'int'>
4 <class 'int'>
6.0 <class 'float'>
7.5 <class 'float'>
234352354 <class 'int'>
the end <class 'str'>
 <class 'str'>
99 <class 'int'>
The amount of elements in the list is 9


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
hello <class 'str'><br/>
2 < class 'int'><br/>
4 < class 'int'><br/>
6.0 < class 'float'><br/>
7.5 < class 'float'><br/>
234352354 < class 'int'><br/>
the end < class 'str'><br/>
 < class 'str'><br/>
99 < class 'int'><br />
The number of elements in the list is 9</span>

### Problem 3
Write code that iterates over to the string _sentence_ and does the following:
1. Count the number of characters using the variable _numChars_.
2. Count the number of vowels using the variable _numVowels_. A character is a vowel if it is a member of the tuple _vowels_. 

Print the variables _numChars_ and _numVowels_ preceded by appropriate labels as shown below. 

Do NOT use the **len** function to solve the problem.  You may use the **len** function on the string to confirm the your answer is correct. 

In [72]:
sentence = "The quick brown rhino jumped over the extremely lazy fox."
vowels = ('a','e','i','o','u')
# Write your code below.
numChars = 0

for char in sentence:
    numChars += 1
    
print("The amount of characters is", numChars)

numVowels = 0
for vowel in sentence:
    if vowel in vowels:
        numVowels += 1
        
print("The amount of vowels is", numVowels)


The amount of characters is 57
The amount of vowels is 16


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The number of characters is  57<br />
The number of vowels is  16
</span>

### Problem 4

Write code in the cell below that does the following:
1. Create a list called _words_ from the words in the string _sentence_.
2. Iterate over _words_ 
    1. Create a list called wordLens which contains the length of every element in _words_.
    2. Count the number of words in _words_ in the variable _numWords_.
    3. Print the word and the word length.

You need one loop to solve this problem.  You need to use the **len** and **split** function. Print the list _wordLens_ and the variable _numWords_ as shown below. 

In [62]:
sentence = "The quick brown rhino jumped over the extremely lazy fox"

# Write your code below.
words = sentence.split()
counter = 0
wordLens = len(words)
counterList = []

for x in words:
    print(x, len(x))
    counter = counter + 1
    counterList = counterList + [len(x)]
    
print("The amount of words is", wordLens)

print(counterList)

The 3
quick 5
brown 5
rhino 5
jumped 6
over 4
the 3
extremely 9
lazy 4
fox 3
The amount of words is 10
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The 3<br/>
quick 5<br/>
brown 5<br/>
rhino 5<br/>
jumped 6<br/>
over 4<br/>
the 3<br/>
extremely 9<br/>
lazy 4<br/>
fox 3<br/>
Number of words is 10<br/>
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]</span>

### Problem 5

The string _addStr_ contains list of numbers separated by the plus sign. Write code that uses an accumulation pattern to take the sum of all numbers and assigns it to the variable sumVal.  Print the variable sumVal prefixed by an appropriate label. 

You should use the **split** function to split by "+" and int() to cast to an integer.

In [63]:
addStr = "2+5+10+20"

# Write your code below.
addStr = addStr.split("+")
sumVal = 0
for num in addStr:
    sumVal = sumVal + int(num)
    
print ("The total of all numbers is", sumVal)

The total of all numbers is 37


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The total of all numbers is 37</span>

### Problem 6

The string _weekTemps_ contains a comma-separated list of fahrenheit temperatures.  Write code that computes the average temperature and assign it to the variable _avgTemp_. Do not hard code your answer.  This means that your code must compute both the total of all temperatures and the number of temperatures in _weekTemps_. The average temperature is defined as the total of all temperatures divided by the number of temperatures. Print the variable _avgTemp_ preceded by an appropriate label.

You need to use one loop to solve this problem. You need to use the **split** and **float** functions.  

In [64]:
weekTemps = "75.1,77.7,83.2,82.5,81.0,79.5,85.7"

# Write your code below.
weekTemps = weekTemps.split(",")
counter = 0
total = 0

for num in weekTemps:
    counter += 1
    total = total + float(num)
avgTemp = total / counter

print ("The average temperature is", float(avgTemp))

The average temperature is 80.67142857142858


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The average temperature is 80.67142857142858</span>

### Problem 7

The variable _rainfallMI_ is a string of comma-separated values.  Each value is the monthly average rainfall in inches for Michigan. Write code that does the following:
1. Compute the number of months that have more than 3 inches of rainfall. Store the result in the variable _numRainyMonths_. 
2. Compute the total rainfall for all months.  Store the result in the variable _totRainfall_. 

Print the variables _numRainyMonths_ and _avgRainfall_ with the appropriate label as shown below.

In [65]:
rainfallMI = "1.65, 1.46, 2.05, 3.03, 3.35, 3.46, 2.83, 3.23, 3.5, 2.52, 2.8, 1.85"

# Write your code below.
rainfallMI = rainfallMI.split(",")
numRainyMonths = 0
totRainfall = 0

for num in rainfallMI:
    if float(num) > 3:
        numRainyMonths += 1
    totRainfall = totRainfall + float(num)
    
print ("The number of months with greater than 3 inches of rain is", int(numRainyMonths))
print ("The total amount of rainfall for all months is", float(totRainfall))



The number of months with greater than 3 inches of rain is 5
The total amount of rainfall for all months is 31.73


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Number of months with more than 3 inches of rain 5<br />
Total rainfall for all months is 31.73</span>

### Problem 8

The variable _sentence_ stores a string of words. Write code that does the following:
1. Compute the number of words that begin and end with the same letter including one-letter words. Store the result in the variable _sameLetterCount_.
2. Compute that number of word that contain an "f" or a "k".  Store the result in the variable _fkCount_. 

Print the variables _sameLetterCount_ and _fkCount_ as shown below. 

You need to use **split**, the **in** operator to test for the existence of an "f" or "k", the **or** operator to join the logical expressions when testing for the existence of the letters. 

In [66]:
sentence = "students flock to the arb for a variety of outdoor activities such as jogging and picnicking"

# write your code below
sentence = sentence.split(" ")
sameLetterCount = 0
fkCount = 0

for word in sentence:
    if word[0] == word[-1]:
        sameLetterCount += 1
    if word.count("f") or word.count("k") > 0 :
         fkCount += 1
            
print ("The number of words that begin and end with the same letter is", int(sameLetterCount))
print ("The number of words that have f or k is", int(fkCount))

The number of words that begin and end with the same letter is 2
The number of words that have f or k is 4


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
The number of words that begin and end with the same letter is 2<br />
The number of words that contain f or k is 4</span>

### Problem 9

Write code that does the followsin:
1. Compute the number of words in variable _sentence_ that contain either an "p" or an "g". Store the result in the variable _numPorG_.  
2. Creates a string _strPorG_ composed of those words in _sentence_ that contain an "p" or "g". Each word in _strPorG_ must be separated by a comma.

Print the variables _numPorG_ and _strPorG_ as shown below.

Do not double-count words that contain both an p and an g. Use the **in** operator to test for existence. 

In [67]:
sentence = "python is a high level general purpose programming language that can be applied to many different classes of problems"

# write your code below
sentence = sentence.split(" ")
numPorG = 0
strPorG = ""

for word in sentence:
    if "p" in word or "g" in word:
        numPorG += 1
        strPorG += word + ","
        
print ("The amount of words containing p or g is", numPorG)
print ("The words are", strPorG)


The amount of words containing p or g is 8
The words are python,high,general,purpose,programming,language,applied,problems,


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Number of words containing p or g is 8<br />
Those words are python,high,general,purpose,programming,language,applied,problems</span>

### Problem 10

Write code that iterates over the list _months_ does the following:
1. Displays the elements in the list _months_ and _rainfallMI_ as a two column table as shown below.
2. Finds and displays the month with the largest rainfall. Stores the results in the variables _maxRain_ and _maxMonth_.
3. Finds and displays the month with the lowest rainfall. Stores the results in the variables _minRain_ and _minMonth_.
4. Total the rainfall for the year and store the result in _totRain_.

The month must printed  left-justified and the rainfall_mi right-justified.  You must use string formatting.

Since you can only iterate over one sequence at a time.  You need to manually index into the list _rainfallMI as you iterate over the first. Also, you must use only one for loop.

In [68]:
rainfallMI = ['1.65', ' 1.46', ' 2.05', ' 3.03', ' 3.35', ' 3.46', ' 2.83', ' 3.23',
               ' 3.5', ' 2.52', ' 2.8', ' 1.85']
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

# Write your code below.
output_format = '{0} {1:5.2f}'
print("Mon Rainfall")
maxRain = None
minRain = None
index = 0
totRain = 0.0

for svalue in rainfallMI:
    value = float(svalue)
    
    if maxRain==None or value > maxRain:
        maxRain = value
        maxMonth = index
        
    if minRain==None or value < minRain:
        minRain = value
        minMonth = index
        
    print(output_format.format(months[index],value))
    index = index + 1
    totRain = totRain + value
    
output_format_2 ='{0:.2f}'

print("The month with the largest rainfall is",months[maxMonth],"with a rainfall of",output_format_2.format(maxRain))

print("The month with the lowest rainfall is",months[minMonth],"with a rainfall of",output_format_2.format(minRain))

print("The annual rainfall is", totRain)

Mon Rainfall
Jan  1.65
Feb  1.46
Mar  2.05
Apr  3.03
May  3.35
Jun  3.46
Jul  2.83
Aug  3.23
Sep  3.50
Oct  2.52
Nov  2.80
Dec  1.85
The month with the largest rainfall is Sep with a rainfall of 3.50
The month with the lowest rainfall is Feb with a rainfall of 1.46
The annual rainfall is 31.73


<span style="color:blue">Expected output:</span><br/>
<span style="font: courier; font-size: 13px">
Mon Rainfall<br/>
Jan 1.65<br/>
Feb 1.46<br/>
Mar 2.05<br/>
Apr 3.03<br/>
May 3.35<br/>
Jun 3.46<br/>
Jul 2.83<br/>
Aug 3.23<br/>
Sep 3.50<br/>
Oct 2.52<br/>
Nov 2.80<br/>
Dec 1.85<br/>
The month with the largest rainfall is Sep with a rainfall of 3.50<br/>
The month with the lowest rainfall is Feb with a rainfall of 1.46<br/>
The annual rainfall is 31.73<br/></span>

### <span style="color:dark green">Run the cells below to test your code</span>

In [70]:
import unittest

class PS03_01 (unittest.TestCase):
    def test_problem01(self):
        self.assertEqual(cntChars, 8)
class PS03_02 (unittest.TestCase):
    def test_problem02(self):
        self.assertEqual(cntList, 9)
class PS03_03 (unittest.TestCase):
    def test_problem03(self):
        self.assertEqual(numChars, 57)
        self.assertEqual(numVowels, 16)
class PS03_04 (unittest.TestCase):
    def test_problem04(self):
        self.assertEqual(numWords, 10)
        self.assertEqual(sum(wordLens), 47)
class PS03_05 (unittest.TestCase):
    def test_problem05(self):
        self.assertEqual(sumVal, 37)
class PS03_06 (unittest.TestCase):
    def test_problem06(self):
        self.assertEqual(round(avgTemp), 81)
class PS03_07 (unittest.TestCase):
    def test_problem07(self):
        self.assertEqual(numRainyMonths5, 5)
        self.assertEqual(round(totRainfall), 32)
class PS03_08 (unittest.TestCase):
    def test_problem08(self):
        self.assertEqual(sameLetterCount, 2)
        self.assertEqual(fkCount, 4)
class PS03_09 (unittest.TestCase):
    def test_problem09(self):
        self.assertEqual(numPorG, 8)
        self.assertEqual(len(strPorG.split(',')), 8)
class PS03_10 (unittest.TestCase):
    def test_problem10(self):
        self.assertEqual(maxRain, 3.50)
        self.assertEqual(maxMonth, 'Sep')
        self.assertEqual(minRain, 1.46)
        self.assertEqual(minMonth, 'Feb')
        self.assertEqual(totRain, 31.73)

In [39]:
unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)

test_problem01 (__main__.PS03_01) ... ok
test_problem02 (__main__.PS03_02) ... ok
test_problem03 (__main__.PS03_03) ... FAIL
test_problem04 (__main__.PS03_04) ... ERROR
test_problem05 (__main__.PS03_05) ... ok
test_problem06 (__main__.PS03_06) ... ok
test_problem07 (__main__.PS03_07) ... ERROR
test_problem08 (__main__.PS03_08) ... ok
test_problem09 (__main__.PS03_09) ... FAIL
test_problem10 (__main__.PS03_10) ... FAIL

ERROR: test_problem04 (__main__.PS03_04)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-38-fe6513c51092>", line 15, in test_problem04
    self.assertEqual(numWords, 10)
NameError: name 'numWords' is not defined

ERROR: test_problem07 (__main__.PS03_07)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-38-fe6513c51092>", line 25, in test_problem07
    self.assertEqual(numRainyMonths5, 5)
NameError: name 'numRainyM